version: "3.8"

volumes:
  mongo_data:

networks:
  app-network:
  db-network:

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    depends_on:
      - backend
    stdin_open: true
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - "3000"
    networks:
      - app-network
      - db-network
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:4.2.0
    volumes:
      - mongo_data:/data/db
    expose:
      - "27017"
    networks:
      - db-network
    restart: unless-stopped