version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: exemplo
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario123
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - rede-local

  backend:
    build: ./backend
    container_name: app-backend
    ports:
      - "3001:3000"
    depends_on:
      - db
    networks:
      - rede-local

volumes:
  dbdata:  # Volume persistente para os dados do MySQL

networks:
  rede-local:
    driver: bridge